server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: main # rama donde estaremos trabajando con el proyecto
          uri: https://github.com/Andre-Moreno-Zamora/configservertest # URI del repositorio
          search-paths: config-data # Carpeta que contiene los archivos de configuración de los microservicios
  application:
    name: config-service